//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFWEB.ProxyCitasService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCitasService.ICitasService")]
    public interface ICitasService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICitasService/ObtenerCitaPorPacientes", ReplyAction="http://tempuri.org/ICitasService/ObtenerCitaPorPacientesResponse")]
        System.Data.DataSet ObtenerCitaPorPacientes(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICitasService/ObtenerCitaPorPacientes", ReplyAction="http://tempuri.org/ICitasService/ObtenerCitaPorPacientesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerCitaPorPacientesAsync(string dni);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICitasServiceChannel : WCFWEB.ProxyCitasService.ICitasService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CitasServiceClient : System.ServiceModel.ClientBase<WCFWEB.ProxyCitasService.ICitasService>, WCFWEB.ProxyCitasService.ICitasService {
        
        public CitasServiceClient() {
        }
        
        public CitasServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CitasServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CitasServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CitasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ObtenerCitaPorPacientes(string dni) {
            return base.Channel.ObtenerCitaPorPacientes(dni);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerCitaPorPacientesAsync(string dni) {
            return base.Channel.ObtenerCitaPorPacientesAsync(dni);
        }
    }
}
