//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public Cita()
        {
            this.Diagnostico = new HashSet<Diagnostico>();
        }
    
        public string codigo_cita { get; set; }
        public string codigo_paciente { get; set; }
        public string codigo_sala { get; set; }
        public string servicio { get; set; }
        public decimal pago { get; set; }
        public string codigo_medico { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Orden { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
    
        public virtual ICollection<Diagnostico> Diagnostico { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
