//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ClinicaEntities3 : DbContext
    {
        public ClinicaEntities3()
            : base("name=ClinicaEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cita> Cita { get; set; }
        public DbSet<Diagnostico> Diagnostico { get; set; }
        public DbSet<Distritos> Distritos { get; set; }
        public DbSet<Doctor> Doctor { get; set; }
        public DbSet<Enfermedad> Enfermedad { get; set; }
        public DbSet<Especialidad> Especialidad { get; set; }
        public DbSet<HorarioAtencion> HorarioAtencion { get; set; }
        public DbSet<Pacientes> Pacientes { get; set; }
        public DbSet<Sala> Sala { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual int sp_ActualizarCita(string vcod, string codpa, string serv, Nullable<decimal> pago, string come, Nullable<System.DateTime> fecr, string ord, Nullable<System.DateTime> feca)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            var codpaParameter = codpa != null ?
                new ObjectParameter("codpa", codpa) :
                new ObjectParameter("codpa", typeof(string));
    
            var servParameter = serv != null ?
                new ObjectParameter("serv", serv) :
                new ObjectParameter("serv", typeof(string));
    
            var pagoParameter = pago.HasValue ?
                new ObjectParameter("pago", pago) :
                new ObjectParameter("pago", typeof(decimal));
    
            var comeParameter = come != null ?
                new ObjectParameter("come", come) :
                new ObjectParameter("come", typeof(string));
    
            var fecrParameter = fecr.HasValue ?
                new ObjectParameter("fecr", fecr) :
                new ObjectParameter("fecr", typeof(System.DateTime));
    
            var ordParameter = ord != null ?
                new ObjectParameter("ord", ord) :
                new ObjectParameter("ord", typeof(string));
    
            var fecaParameter = feca.HasValue ?
                new ObjectParameter("feca", feca) :
                new ObjectParameter("feca", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarCita", vcodParameter, codpaParameter, servParameter, pagoParameter, comeParameter, fecrParameter, ordParameter, fecaParameter);
        }
    
        public virtual int sp_ActualizarMedico(string vcod, string nom, string ape, string dire, string telf, string ema, string code, string codh)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("ape", ape) :
                new ObjectParameter("ape", typeof(string));
    
            var direParameter = dire != null ?
                new ObjectParameter("dire", dire) :
                new ObjectParameter("dire", typeof(string));
    
            var telfParameter = telf != null ?
                new ObjectParameter("telf", telf) :
                new ObjectParameter("telf", typeof(string));
    
            var emaParameter = ema != null ?
                new ObjectParameter("ema", ema) :
                new ObjectParameter("ema", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var codhParameter = codh != null ?
                new ObjectParameter("codh", codh) :
                new ObjectParameter("codh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarMedico", vcodParameter, nomParameter, apeParameter, direParameter, telfParameter, emaParameter, codeParameter, codhParameter);
        }
    
        public virtual int sp_ActualizarPacientes(string vcod, string nom, string ape, Nullable<System.DateTime> fecnac, string sex, string cods, string pais, string codd, string emer, string ocup, string aler)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("ape", ape) :
                new ObjectParameter("ape", typeof(string));
    
            var fecnacParameter = fecnac.HasValue ?
                new ObjectParameter("fecnac", fecnac) :
                new ObjectParameter("fecnac", typeof(System.DateTime));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            var codsParameter = cods != null ?
                new ObjectParameter("cods", cods) :
                new ObjectParameter("cods", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var coddParameter = codd != null ?
                new ObjectParameter("codd", codd) :
                new ObjectParameter("codd", typeof(string));
    
            var emerParameter = emer != null ?
                new ObjectParameter("emer", emer) :
                new ObjectParameter("emer", typeof(string));
    
            var ocupParameter = ocup != null ?
                new ObjectParameter("ocup", ocup) :
                new ObjectParameter("ocup", typeof(string));
    
            var alerParameter = aler != null ?
                new ObjectParameter("aler", aler) :
                new ObjectParameter("aler", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarPacientes", vcodParameter, nomParameter, apeParameter, fecnacParameter, sexParameter, codsParameter, paisParameter, coddParameter, emerParameter, ocupParameter, alerParameter);
        }
    
        public virtual int sp_AgregarHorario(string codho, Nullable<System.DateTime> fecaini, Nullable<System.DateTime> fecafin)
        {
            var codhoParameter = codho != null ?
                new ObjectParameter("codho", codho) :
                new ObjectParameter("codho", typeof(string));
    
            var fecainiParameter = fecaini.HasValue ?
                new ObjectParameter("fecaini", fecaini) :
                new ObjectParameter("fecaini", typeof(System.DateTime));
    
            var fecafinParameter = fecafin.HasValue ?
                new ObjectParameter("fecafin", fecafin) :
                new ObjectParameter("fecafin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AgregarHorario", codhoParameter, fecainiParameter, fecafinParameter);
        }
    
        public virtual int sp_AgregarMedico(string nom, string ape, string dire, string telf, string ema, string code, string codh)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("ape", ape) :
                new ObjectParameter("ape", typeof(string));
    
            var direParameter = dire != null ?
                new ObjectParameter("dire", dire) :
                new ObjectParameter("dire", typeof(string));
    
            var telfParameter = telf != null ?
                new ObjectParameter("telf", telf) :
                new ObjectParameter("telf", typeof(string));
    
            var emaParameter = ema != null ?
                new ObjectParameter("ema", ema) :
                new ObjectParameter("ema", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var codhParameter = codh != null ?
                new ObjectParameter("codh", codh) :
                new ObjectParameter("codh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AgregarMedico", nomParameter, apeParameter, direParameter, telfParameter, emaParameter, codeParameter, codhParameter);
        }
    
        public virtual int sp_AgregarPaciente(string nom, string ape, Nullable<System.DateTime> fecnac, string sex, string cods, string pais, string codd, string emer, string ocup, string aler)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("ape", ape) :
                new ObjectParameter("ape", typeof(string));
    
            var fecnacParameter = fecnac.HasValue ?
                new ObjectParameter("fecnac", fecnac) :
                new ObjectParameter("fecnac", typeof(System.DateTime));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            var codsParameter = cods != null ?
                new ObjectParameter("cods", cods) :
                new ObjectParameter("cods", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var coddParameter = codd != null ?
                new ObjectParameter("codd", codd) :
                new ObjectParameter("codd", typeof(string));
    
            var emerParameter = emer != null ?
                new ObjectParameter("emer", emer) :
                new ObjectParameter("emer", typeof(string));
    
            var ocupParameter = ocup != null ?
                new ObjectParameter("ocup", ocup) :
                new ObjectParameter("ocup", typeof(string));
    
            var alerParameter = aler != null ?
                new ObjectParameter("aler", aler) :
                new ObjectParameter("aler", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AgregarPaciente", nomParameter, apeParameter, fecnacParameter, sexParameter, codsParameter, paisParameter, coddParameter, emerParameter, ocupParameter, alerParameter);
        }
    
        public virtual ObjectResult<sp_CitasPaciente_Result> sp_CitasPaciente(string codPaciente)
        {
            var codPacienteParameter = codPaciente != null ?
                new ObjectParameter("codPaciente", codPaciente) :
                new ObjectParameter("codPaciente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CitasPaciente_Result>("sp_CitasPaciente", codPacienteParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarDistritos_Result> sp_ConsultarDistritos(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarDistritos_Result>("sp_ConsultarDistritos", vcodParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarEnfermedad_Result> sp_ConsultarEnfermedad(string ecod)
        {
            var ecodParameter = ecod != null ?
                new ObjectParameter("ecod", ecod) :
                new ObjectParameter("ecod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarEnfermedad_Result>("sp_ConsultarEnfermedad", ecodParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarHorarios_Result> sp_ConsultarHorarios(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarHorarios_Result>("sp_ConsultarHorarios", vcodParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarMedicos_Result> sp_ConsultarMedicos(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarMedicos_Result>("sp_ConsultarMedicos", vcodParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarPacientes_Result> sp_ConsultarPacientes(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarPacientes_Result>("sp_ConsultarPacientes", vcodParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarSala_Result> sp_ConsultarSala(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarSala_Result>("sp_ConsultarSala", vcodParameter);
        }
    
        public virtual ObjectResult<sp_DoctorxCitas_Result> sp_DoctorxCitas(string codDoctor, string servicio)
        {
            var codDoctorParameter = codDoctor != null ?
                new ObjectParameter("codDoctor", codDoctor) :
                new ObjectParameter("codDoctor", typeof(string));
    
            var servicioParameter = servicio != null ?
                new ObjectParameter("servicio", servicio) :
                new ObjectParameter("servicio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DoctorxCitas_Result>("sp_DoctorxCitas", codDoctorParameter, servicioParameter);
        }
    
        public virtual int sp_EliminarCita(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarCita", vcodParameter);
        }
    
        public virtual int sp_EliminarMedico(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarMedico", vcodParameter);
        }
    
        public virtual int sp_EliminarPacientes(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarPacientes", vcodParameter);
        }
    
        public virtual ObjectResult<sp_ListarCantidadEnfermedasdesPaises_Result> sp_ListarCantidadEnfermedasdesPaises(string codEnfermedad)
        {
            var codEnfermedadParameter = codEnfermedad != null ?
                new ObjectParameter("codEnfermedad", codEnfermedad) :
                new ObjectParameter("codEnfermedad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCantidadEnfermedasdesPaises_Result>("sp_ListarCantidadEnfermedasdesPaises", codEnfermedadParameter);
        }
    
        public virtual ObjectResult<sp_ListarCantidadEnfermedasdesPaises2_Result> sp_ListarCantidadEnfermedasdesPaises2(string pais)
        {
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCantidadEnfermedasdesPaises2_Result>("sp_ListarCantidadEnfermedasdesPaises2", paisParameter);
        }
    
        public virtual ObjectResult<sp_ListarCitas_Result> sp_ListarCitas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCitas_Result>("sp_ListarCitas");
        }
    
        public virtual ObjectResult<sp_ListarCitaxFechaxServicio_Result> sp_ListarCitaxFechaxServicio(string codEspec, string sex, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin)
        {
            var codEspecParameter = codEspec != null ?
                new ObjectParameter("codEspec", codEspec) :
                new ObjectParameter("codEspec", typeof(string));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCitaxFechaxServicio_Result>("sp_ListarCitaxFechaxServicio", codEspecParameter, sexParameter, fec_iniParameter, fec_finParameter);
        }
    
        public virtual ObjectResult<sp_ListarDistrito_Result> sp_ListarDistrito()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarDistrito_Result>("sp_ListarDistrito");
        }
    
        public virtual ObjectResult<sp_ListarEnfermedades_Result> sp_ListarEnfermedades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarEnfermedades_Result>("sp_ListarEnfermedades");
        }
    
        public virtual ObjectResult<sp_ListarEnfermedadesFechas_Result> sp_ListarEnfermedadesFechas(string cod_enf, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin)
        {
            var cod_enfParameter = cod_enf != null ?
                new ObjectParameter("cod_enf", cod_enf) :
                new ObjectParameter("cod_enf", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarEnfermedadesFechas_Result>("sp_ListarEnfermedadesFechas", cod_enfParameter, fec_iniParameter, fec_finParameter);
        }
    
        public virtual ObjectResult<sp_ListarEnfermedadesMedicamento_Result> sp_ListarEnfermedadesMedicamento(string cod_enf)
        {
            var cod_enfParameter = cod_enf != null ?
                new ObjectParameter("cod_enf", cod_enf) :
                new ObjectParameter("cod_enf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarEnfermedadesMedicamento_Result>("sp_ListarEnfermedadesMedicamento", cod_enfParameter);
        }
    
        public virtual ObjectResult<sp_ListarEnfermedadesMedicamentocontando_Result> sp_ListarEnfermedadesMedicamentocontando(string cod_enf)
        {
            var cod_enfParameter = cod_enf != null ?
                new ObjectParameter("cod_enf", cod_enf) :
                new ObjectParameter("cod_enf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarEnfermedadesMedicamentocontando_Result>("sp_ListarEnfermedadesMedicamentocontando", cod_enfParameter);
        }
    
        public virtual ObjectResult<sp_ListarEspecialidad_Result> sp_ListarEspecialidad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarEspecialidad_Result>("sp_ListarEspecialidad");
        }
    
        public virtual ObjectResult<sp_ListarHorarios_Result> sp_ListarHorarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarHorarios_Result>("sp_ListarHorarios");
        }
    
        public virtual ObjectResult<sp_ListarMedico_Result> sp_ListarMedico()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarMedico_Result>("sp_ListarMedico");
        }
    
        public virtual ObjectResult<sp_ListarMedicoNombre_Result> sp_ListarMedicoNombre(string nom, string ape)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("ape", ape) :
                new ObjectParameter("ape", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarMedicoNombre_Result>("sp_ListarMedicoNombre", nomParameter, apeParameter);
        }
    
        public virtual ObjectResult<sp_ListarPacienteNombre_Result> sp_ListarPacienteNombre(string nom, string ape)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("ape", ape) :
                new ObjectParameter("ape", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarPacienteNombre_Result>("sp_ListarPacienteNombre", nomParameter, apeParameter);
        }
    
        public virtual ObjectResult<sp_ListarPacientepordistrito2_Result> sp_ListarPacientepordistrito2(string cod_enf)
        {
            var cod_enfParameter = cod_enf != null ?
                new ObjectParameter("cod_enf", cod_enf) :
                new ObjectParameter("cod_enf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarPacientepordistrito2_Result>("sp_ListarPacientepordistrito2", cod_enfParameter);
        }
    
        public virtual ObjectResult<sp_ListarPacientePorEnfermedad_Result> sp_ListarPacientePorEnfermedad(string codEnfermedad)
        {
            var codEnfermedadParameter = codEnfermedad != null ?
                new ObjectParameter("codEnfermedad", codEnfermedad) :
                new ObjectParameter("codEnfermedad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarPacientePorEnfermedad_Result>("sp_ListarPacientePorEnfermedad", codEnfermedadParameter);
        }
    
        public virtual ObjectResult<sp_ListarPacientes_Result> sp_ListarPacientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarPacientes_Result>("sp_ListarPacientes");
        }
    
        public virtual ObjectResult<sp_ListarPaisRegistrados_Result> sp_ListarPaisRegistrados(string pais)
        {
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarPaisRegistrados_Result>("sp_ListarPaisRegistrados", paisParameter);
        }
    
        public virtual ObjectResult<sp_ListarSalas_Result> sp_ListarSalas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarSalas_Result>("sp_ListarSalas");
        }
    
        public virtual ObjectResult<string> sp_ListarServicio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_ListarServicio");
        }
    
        public virtual ObjectResult<sp_ListarxPacientexSexoxFecha_Result> sp_ListarxPacientexSexoxFecha(string sex, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin)
        {
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxPacientexSexoxFecha_Result>("sp_ListarxPacientexSexoxFecha", sexParameter, fec_iniParameter, fec_finParameter);
        }
    
        public virtual ObjectResult<sp_ListaxCantidadxCitasxPacientes_Result> sp_ListaxCantidadxCitasxPacientes(string sala, string sexo)
        {
            var salaParameter = sala != null ?
                new ObjectParameter("Sala", sala) :
                new ObjectParameter("Sala", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListaxCantidadxCitasxPacientes_Result>("sp_ListaxCantidadxCitasxPacientes", salaParameter, sexoParameter);
        }
    
        public virtual ObjectResult<sp_ReportePaciente_Result> sp_ReportePaciente(string nom, string ape, string noms)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("ape", ape) :
                new ObjectParameter("ape", typeof(string));
    
            var nomsParameter = noms != null ?
                new ObjectParameter("noms", noms) :
                new ObjectParameter("noms", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ReportePaciente_Result>("sp_ReportePaciente", nomParameter, apeParameter, nomsParameter);
        }
    
        public virtual ObjectResult<sp_ReportMedico_Result> sp_ReportMedico(Nullable<int> desde, Nullable<int> hasta)
        {
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(int));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ReportMedico_Result>("sp_ReportMedico", desdeParameter, hastaParameter);
        }
    
        public virtual ObjectResult<sp_ListarCantidadEnfermedasdesPaises_Result> ListarCantidadEnfermedadesPaises(string codEnfermedad)
        {
            var codEnfermedadParameter = codEnfermedad != null ?
                new ObjectParameter("codEnfermedad", codEnfermedad) :
                new ObjectParameter("codEnfermedad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCantidadEnfermedasdesPaises_Result>("ListarCantidadEnfermedadesPaises", codEnfermedadParameter);
        }
    
        public virtual ObjectResult<sp_ListarCitaxFechaxServicio_Result> ListarCitaFechaServicio(string codEspec, string sex, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin)
        {
            var codEspecParameter = codEspec != null ?
                new ObjectParameter("codEspec", codEspec) :
                new ObjectParameter("codEspec", typeof(string));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCitaxFechaxServicio_Result>("ListarCitaFechaServicio", codEspecParameter, sexParameter, fec_iniParameter, fec_finParameter);
        }
    
        public virtual ObjectResult<sp_DoctorxCitas_Result> ListarDoctorXcita(string codDoctor, string servicio)
        {
            var codDoctorParameter = codDoctor != null ?
                new ObjectParameter("codDoctor", codDoctor) :
                new ObjectParameter("codDoctor", typeof(string));
    
            var servicioParameter = servicio != null ?
                new ObjectParameter("servicio", servicio) :
                new ObjectParameter("servicio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DoctorxCitas_Result>("ListarDoctorXcita", codDoctorParameter, servicioParameter);
        }
    
        public virtual ObjectResult<sp_ListaxDoctorxHoraAtencion_Result1> sp_ListaxDoctorxHoraAtencion(string codDoctor, string sexo, string pais, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin)
        {
            var codDoctorParameter = codDoctor != null ?
                new ObjectParameter("codDoctor", codDoctor) :
                new ObjectParameter("codDoctor", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListaxDoctorxHoraAtencion_Result1>("sp_ListaxDoctorxHoraAtencion", codDoctorParameter, sexoParameter, paisParameter, fec_iniParameter, fec_finParameter);
        }
    
        public virtual ObjectResult<sp_ListaxDoctorxHoraAtencion_Result1> ListaDoctor2(string codDoctor, string sexo, string pais, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin)
        {
            var codDoctorParameter = codDoctor != null ?
                new ObjectParameter("codDoctor", codDoctor) :
                new ObjectParameter("codDoctor", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListaxDoctorxHoraAtencion_Result1>("ListaDoctor2", codDoctorParameter, sexoParameter, paisParameter, fec_iniParameter, fec_finParameter);
        }
    
        public virtual ObjectResult<sp_ListaxCantidadxCitasxPacientes2_Result> sp_ListaxCantidadxCitasxPacientes2(string sala, string sexo)
        {
            var salaParameter = sala != null ?
                new ObjectParameter("Sala", sala) :
                new ObjectParameter("Sala", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListaxCantidadxCitasxPacientes2_Result>("sp_ListaxCantidadxCitasxPacientes2", salaParameter, sexoParameter);
        }
    
        public virtual ObjectResult<sp_ListaxCantidadxCitasxPacientes2_Result> ListaCantidadCitasPacientes2(string sala, string sexo)
        {
            var salaParameter = sala != null ?
                new ObjectParameter("Sala", sala) :
                new ObjectParameter("Sala", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListaxCantidadxCitasxPacientes2_Result>("ListaCantidadCitasPacientes2", salaParameter, sexoParameter);
        }
    
        public virtual ObjectResult<sp_listarpacientes2_Result> sp_listarpacientes2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listarpacientes2_Result>("sp_listarpacientes2");
        }
    
        public virtual ObjectResult<sp_listarpacientes2_Result> ListaPacientes2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listarpacientes2_Result>("ListaPacientes2");
        }
    
        public virtual ObjectResult<sp_ListarxPacientexSexoxFecha2_Result> sp_ListarxPacientexSexoxFecha2(string sex, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin)
        {
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxPacientexSexoxFecha2_Result>("sp_ListarxPacientexSexoxFecha2", sexParameter, fec_iniParameter, fec_finParameter);
        }
    
        public virtual ObjectResult<sp_ListarxPacientexSexoxFecha2_Result> ListarxPacientexSexoxFecha2(string sex, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin)
        {
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxPacientexSexoxFecha2_Result>("ListarxPacientexSexoxFecha2", sexParameter, fec_iniParameter, fec_finParameter);
        }
    
        public virtual ObjectResult<sp_ListarxPacientexSexoxFecha3_Result> sp_ListarxPacientexSexoxFecha3(string sex, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin)
        {
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxPacientexSexoxFecha3_Result>("sp_ListarxPacientexSexoxFecha3", sexParameter, fec_iniParameter, fec_finParameter);
        }
    
        public virtual ObjectResult<sp_ListarxPacientexSexoxFecha3_Result> ListarxPacientexSexoxFecha3(string sex, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin)
        {
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxPacientexSexoxFecha3_Result>("ListarxPacientexSexoxFecha3", sexParameter, fec_iniParameter, fec_finParameter);
        }
    
        public virtual ObjectResult<sp_ListarxPacientexSexoxFechaxDistrito_Result> sp_ListarxPacientexSexoxFechaxDistrito(string sex, string dis, Nullable<System.DateTime> fec_ini, Nullable<System.DateTime> fec_fin)
        {
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var disParameter = dis != null ?
                new ObjectParameter("Dis", dis) :
                new ObjectParameter("Dis", typeof(string));
    
            var fec_iniParameter = fec_ini.HasValue ?
                new ObjectParameter("fec_ini", fec_ini) :
                new ObjectParameter("fec_ini", typeof(System.DateTime));
    
            var fec_finParameter = fec_fin.HasValue ?
                new ObjectParameter("fec_fin", fec_fin) :
                new ObjectParameter("fec_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxPacientexSexoxFechaxDistrito_Result>("sp_ListarxPacientexSexoxFechaxDistrito", sexParameter, disParameter, fec_iniParameter, fec_finParameter);
        }
    
        public virtual ObjectResult<sp_ListarxCantidadxPacientexSexoxDistrito_Result> sp_ListarxCantidadxPacientexSexoxDistrito(string sex, string dis)
        {
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var disParameter = dis != null ?
                new ObjectParameter("dis", dis) :
                new ObjectParameter("dis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxCantidadxPacientexSexoxDistrito_Result>("sp_ListarxCantidadxPacientexSexoxDistrito", sexParameter, disParameter);
        }
    
        public virtual ObjectResult<sp_ListarxCantidadxPacientexSexoxDistrito_Result> ListarxCantidadxPacientexSexoxDistrito(string sex, string dis)
        {
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var disParameter = dis != null ?
                new ObjectParameter("dis", dis) :
                new ObjectParameter("dis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxCantidadxPacientexSexoxDistrito_Result>("ListarxCantidadxPacientexSexoxDistrito", sexParameter, disParameter);
        }
    
        public virtual ObjectResult<sp_ListarxCantidadxPacientexSexoxDistrito2_Result> sp_ListarxCantidadxPacientexSexoxDistrito2(string sex, string dis)
        {
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var disParameter = dis != null ?
                new ObjectParameter("dis", dis) :
                new ObjectParameter("dis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxCantidadxPacientexSexoxDistrito2_Result>("sp_ListarxCantidadxPacientexSexoxDistrito2", sexParameter, disParameter);
        }
    
        public virtual ObjectResult<sp_ListarxCantidadxPacientexSexoxDistrito2_Result> ListarxCantidadxPacientexSexoxDistrito2(string sex, string dis)
        {
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var disParameter = dis != null ?
                new ObjectParameter("dis", dis) :
                new ObjectParameter("dis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxCantidadxPacientexSexoxDistrito2_Result>("ListarxCantidadxPacientexSexoxDistrito2", sexParameter, disParameter);
        }
    
        public virtual ObjectResult<sp_ListarxCantidadxPacientexSexoxSala_Result> sp_ListarxCantidadxPacientexSexoxSala(string sal)
        {
            var salParameter = sal != null ?
                new ObjectParameter("sal", sal) :
                new ObjectParameter("sal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxCantidadxPacientexSexoxSala_Result>("sp_ListarxCantidadxPacientexSexoxSala", salParameter);
        }
    
        public virtual ObjectResult<sp_ListarxCantidadxPacientexSexoxSala_Result> ListarxCantidadxPacientexSexoxSala(string sal)
        {
            var salParameter = sal != null ?
                new ObjectParameter("sal", sal) :
                new ObjectParameter("sal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxCantidadxPacientexSexoxSala_Result>("ListarxCantidadxPacientexSexoxSala", salParameter);
        }
    
        public virtual ObjectResult<sp_ListarCantidadPacientesxDistritoxDoctor_Result> sp_ListarCantidadPacientesxDistritoxDoctor(string doc)
        {
            var docParameter = doc != null ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCantidadPacientesxDistritoxDoctor_Result>("sp_ListarCantidadPacientesxDistritoxDoctor", docParameter);
        }
    
        public virtual ObjectResult<sp_ListarCantidadPacientesxSexoxDistritoxDoctor_Result> sp_ListarCantidadPacientesxSexoxDistritoxDoctor(string doc)
        {
            var docParameter = doc != null ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCantidadPacientesxSexoxDistritoxDoctor_Result>("sp_ListarCantidadPacientesxSexoxDistritoxDoctor", docParameter);
        }
    
        public virtual ObjectResult<sp_ListarCantidadPacientesxSexoxDistritoxDoctor_Result> ListarCantidadPacientesxSexoxDistritoxDoctor(string doc)
        {
            var docParameter = doc != null ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCantidadPacientesxSexoxDistritoxDoctor_Result>("ListarCantidadPacientesxSexoxDistritoxDoctor", docParameter);
        }
    
        public virtual ObjectResult<sp_ListarCantidadPacientesxDistritoxDoctor_Result> ListarCantidadPacientesxDistritoxDoctor(string doc)
        {
            var docParameter = doc != null ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCantidadPacientesxDistritoxDoctor_Result>("ListarCantidadPacientesxDistritoxDoctor", docParameter);
        }
    
        public virtual ObjectResult<sp_ListarCantidadPacientesxDistritoxDoctor2_Result> sp_ListarCantidadPacientesxDistritoxDoctor2(string doc)
        {
            var docParameter = doc != null ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCantidadPacientesxDistritoxDoctor2_Result>("sp_ListarCantidadPacientesxDistritoxDoctor2", docParameter);
        }
    
        public virtual ObjectResult<sp_ListarCantidadPacientesxDistritoxDoctor2_Result> ListarCantidadPacientesxDistritoxDoctor2(string doc)
        {
            var docParameter = doc != null ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCantidadPacientesxDistritoxDoctor2_Result>("ListarCantidadPacientesxDistritoxDoctor2", docParameter);
        }
    
        public virtual ObjectResult<sp_ListarxCantidadxPacientexSalaxPaisxServicio_Result> sp_ListarxCantidadxPacientexSalaxPaisxServicio(string servicio)
        {
            var servicioParameter = servicio != null ?
                new ObjectParameter("servicio", servicio) :
                new ObjectParameter("servicio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxCantidadxPacientexSalaxPaisxServicio_Result>("sp_ListarxCantidadxPacientexSalaxPaisxServicio", servicioParameter);
        }
    
        public virtual ObjectResult<sp_ListarxCantidadxPacientexSalaxPaisxServicio_Result> ListarxCantidadxPacientexSalaxPaisxServicio(string servicio)
        {
            var servicioParameter = servicio != null ?
                new ObjectParameter("servicio", servicio) :
                new ObjectParameter("servicio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarxCantidadxPacientexSalaxPaisxServicio_Result>("ListarxCantidadxPacientexSalaxPaisxServicio", servicioParameter);
        }
    }
}
