//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Cita = new HashSet<Cita>();
        }
    
        public string codigo_doctor { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string cod_especialidad { get; set; }
        public string codigo_horarios { get; set; }
    
        public virtual ICollection<Cita> Cita { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        public virtual HorarioAtencion HorarioAtencion { get; set; }
    }
}
