//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        public Pacientes()
        {
            this.Cita = new HashSet<Cita>();
            this.Diagnostico = new HashSet<Diagnostico>();
        }
    
        public string codigo_paciente { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public System.DateTime fecha_nac { get; set; }
        public string sexo { get; set; }
        public string codigo_sala { get; set; }
        public string pais { get; set; }
        public string codigo_distrito { get; set; }
        public string emergencia { get; set; }
        public string ocupacion { get; set; }
        public string alergia { get; set; }
    
        public virtual ICollection<Cita> Cita { get; set; }
        public virtual ICollection<Diagnostico> Diagnostico { get; set; }
        public virtual Distritos Distritos { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
