//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF
{
    using System;
    
    public partial class sp_ListaxDoctorxHoraAtencion_Result1
    {
        public string codigo_cita { get; set; }
        public string Paciente { get; set; }
        public string Sala { get; set; }
        public string Consultorio { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public string pais { get; set; }
    }
}
